name: Nogizaka46

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  Nogizaka46:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Specify the Python version you need
    
      - name: Run apt and pip
        run: |
          sudo apt update
          pip install requests

      - name: Run Python script
        run: |
          python Nogizaka46.py
        env:
          TELEGRAM_CHAT_ID: "-1002350782955"
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
